[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm --filter @momentum/database prisma migrate deploy && pnpm --filter @momentum/web build"

[deploy]
startCommand = "pnpm --filter @momentum/web start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
